import Link from "next/link";
import { ArrowLeft, Bot, MailCheck, Send, Workflow } from "lucide-react";
import { requirePresident } from "@/lib/auth/require-president";
import { createServiceClient } from "@/lib/supabase/server";
import { createAutomationRule, saveEmailTemplate, toggleAutomationRule } from "./actions";

export const dynamic = "force-dynamic";

type Template = { id: string; template_key: string; name: string; description: string | null; subject_template: string; html_template: string; is_system: boolean };
type Sector = { id: string; name: string; is_active: boolean };
type Rule = { id: string; name: string; trigger_key: string; condition_json: { field?: string; equals?: string }; action_json: { type?: string; templateKey?: string }; enabled: boolean; created_at: string; sector: { name: string } | null };
type Run = { id: string; status: string; created_at: string; error_message: string | null; rule: { name: string } | null };

export default async function AutomationsAdminPage() {
  await requirePresident();
  const service = createServiceClient();
  const [{ data: templates }, { data: sectors }, { data: rules }, { data: runs }] = await Promise.all([
    service.from("email_templates").select("id,template_key,name,description,subject_template,html_template,is_system").is("deleted_at", null).order("name").returns<Template[]>(),
    service.from("sectors").select("id,name,is_active").eq("is_active", true).is("deleted_at", null).order("sort_order").returns<Sector[]>(),
    service.from("automation_rules").select("id,name,trigger_key,condition_json,action_json,enabled,created_at,sector:sectors!automation_rules_sector_id_fkey(name)").is("deleted_at", null).order("created_at", { ascending: false }).returns<Rule[]>(),
    service.from("automation_runs").select("id,status,created_at,error_message,rule:automation_rules!automation_runs_rule_id_fkey(name)").order("created_at", { ascending: false }).limit(12).returns<Run[]>(),
  ]);

  return <main className="members-page">
    <header className="members-header"><div><p className="eyebrow eyebrow--blue">PRESIDÊNCIA / AUTOMAÇÕES</p><h1>Regras que deixam rastro.</h1><p>Edite mensagens, crie regras por evento e acompanhe cada execução. O envio passa por fila, prioridade e tentativas controladas.</p></div><Link href="/admin"><ArrowLeft size={16} /> Painel</Link></header>
    <section className="members-summary"><article><Bot size={24} /><span><strong>{(rules ?? []).filter((rule) => rule.enabled).length}</strong><small>regras ativas</small></span></article><article><MailCheck size={24} /><span><strong>{(templates ?? []).length}</strong><small>templates ativos</small></span></article><article><Workflow size={24} /><span><strong>{(runs ?? []).filter((run) => run.status === "succeeded").length}</strong><small>execuções recentes</small></span></article></section>

    <section className="members-layout"><article className="members-invite-card"><div className="members-card-title"><Bot size={19} /><div><span>NOVA REGRA</span><h2>Evento de pedido</h2></div></div><form action={createAutomationRule} className="members-form"><label>Nome<input name="name" required placeholder="Ex.: avisar retirada pronta" /></label><label>Setor responsável<select name="sectorId" defaultValue=""><option value="">Sem setor específico</option>{(sectors ?? []).map((sector) => <option key={sector.id} value={sector.id}>{sector.name}</option>)}</select></label><label>Gatilho<select name="triggerKey" defaultValue="order.status_changed"><option value="order.status_changed">Status de pedido alterado</option></select></label><label>Campo da condição (opcional)<select name="conditionField" defaultValue="status"><option value="">Executar em qualquer status</option><option value="status">Status do pedido</option></select></label><label>Valor esperado<input name="conditionEquals" defaultValue="pronto" placeholder="Ex.: pronto" /></label><label>Ação<select name="actionType" defaultValue="queue_email"><option value="queue_email">Enfileirar e-mail</option><option value="log">Registrar apenas no histórico</option></select></label><label>Template<select name="templateKey" defaultValue="order_status"><option value="">Escolha um template</option>{(templates ?? []).map((template) => <option key={template.id} value={template.template_key}>{template.name}</option>)}</select></label><button type="submit">Criar automação</button></form><p>As regras são idempotentes por evento: uma mesma mudança de pedido não dispara a mesma regra duas vezes.</p></article>
      <section className="members-list-card"><div className="members-list-card__head"><div><span>REGRAS CONFIGURADAS</span><h2>Execução e escopo</h2></div><span>{(rules ?? []).length} regras</span></div><div className="members-table-wrap"><table><thead><tr><th>Regra</th><th>Quando</th><th>Ação</th><th>Estado</th></tr></thead><tbody>{(rules ?? []).map((rule) => <tr key={rule.id}><td><strong>{rule.name}</strong><small>{rule.sector?.name ?? "Escopo geral"}</small></td><td><small>{rule.condition_json?.field ? `${rule.condition_json.field} = ${rule.condition_json.equals || ""}` : "Todo evento do gatilho"}</small></td><td><small>{rule.action_json?.type === "queue_email" ? `E-mail · ${rule.action_json.templateKey}` : "Somente log"}</small></td><td><form action={toggleAutomationRule} className="member-role-form"><input type="hidden" name="id" value={rule.id} /><input type="hidden" name="enabled" value={rule.enabled ? "false" : "true"} /><button type="submit">{rule.enabled ? "Pausar" : "Ativar"}</button></form></td></tr>)}{(rules ?? []).length === 0 && <tr><td colSpan={4} className="members-empty">Nenhuma automação criada.</td></tr>}</tbody></table></div></section></section>

    <section className="members-layout" style={{ marginTop: 20 }}><section className="members-list-card"><div className="members-list-card__head"><div><span>HISTÓRICO</span><h2>Últimas execuções</h2></div><Send size={18} /></div><div className="members-table-wrap"><table><thead><tr><th>Regra</th><th>Resultado</th><th>Quando</th><th>Detalhe</th></tr></thead><tbody>{(runs ?? []).map((run) => <tr key={run.id}><td><strong>{run.rule?.name ?? "Regra removida"}</strong></td><td><span className="member-role member-role--caixa">{run.status}</span></td><td><small>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(run.created_at))}</small></td><td><small>{run.error_message ?? "Sem erro registrado"}</small></td></tr>)}{(runs ?? []).length === 0 && <tr><td colSpan={4} className="members-empty">As execuções aparecerão aqui após o primeiro evento.</td></tr>}</tbody></table></div></section></section>

    <section className="members-list-card" style={{ marginTop: 20 }}><div className="members-list-card__head"><div><span>COMUNICAÇÃO</span><h2>Templates de e-mail</h2></div><span>Use variáveis como {"{{orderNumber}}"}</span></div><div className="members-layout" style={{ padding: 20 }}>{(templates ?? []).map((template) => <article className="members-invite-card" key={template.id}><div className="members-card-title"><MailCheck size={19} /><div><span>{template.is_system ? "SISTEMA" : "PERSONALIZADO"}</span><h2>{template.name}</h2></div></div><form action={saveEmailTemplate} className="members-form"><input type="hidden" name="id" value={template.id} /><label>Assunto<input name="subject" defaultValue={template.subject_template} required /></label><label>Conteúdo HTML<textarea name="html" defaultValue={template.html_template} rows={5} required /></label><button type="submit">Salvar template</button></form><p>{template.description || template.template_key}</p></article>)}</div></section>
  </main>;
}
