import Link from "next/link";
import { ArrowLeft, Database, FilePlus2, Table2, Trash2 } from "lucide-react";
import { requireAdminShell } from "@/lib/auth/require-admin-shell";
import { createServiceClient } from "@/lib/supabase/server";
import { grantMatchesTable } from "@/lib/governance/table-grants";
import { createCustomField, createCustomRecord, createCustomTable, createCustomView, restoreCustomRecord, trashCustomRecord } from "./actions";
import "./tabelas.css";

export const dynamic = "force-dynamic";
type Sector = { id: string; name: string; is_active: boolean };
type CustomTable = { id: string; sector_id: string; name: string; slug: string; description: string | null; sector: Pick<Sector, "name"> | null };
type Field = { id: string; name: string; slug: string; field_type: string; is_required: boolean; config_json: { options?: string[] } };
type RecordRow = { id: string; data_json: Record<string, unknown>; updated_at: string; deleted_at: string | null };

function inputForField(field: Field) {
  const name = `field_${field.slug}`; const required = field.is_required;
  if (["single_select", "multi_select"].includes(field.field_type)) return <select name={name} required={required} multiple={field.field_type === "multi_select"}><option value="">Selecione</option>{(field.config_json.options ?? []).map((option) => <option key={option} value={option}>{option}</option>)}</select>;
  if (field.field_type === "checkbox") return <input name={name} type="checkbox" aria-label={field.name} />;
  return <input name={name} required={required} type={field.field_type === "number" ? "number" : field.field_type === "date" ? "date" : "text"} />;
}

export default async function TableBuilderPage({ searchParams }: { searchParams: Promise<{ table?: string; trash?: string }> }) {
  const params = await searchParams; const session = await requireAdminShell();
  if (!session.canAccessBuilder) return <main className="members-page"><p className="members-empty">Você não possui permissão para abrir tabelas de setor.</p></main>;
  const service = createServiceClient();
  const [{ data: sectors }, { data: memberships }, { data: grants }, { data: rawTables }] = await Promise.all([
    service.from("sectors").select("id,name,is_active").eq("is_active", true).order("sort_order").returns<Sector[]>(),
    service.from("sector_memberships").select("sector_id,role").eq("profile_id", session.userId).is("ended_at", null),
    service.from("permission_grants").select("sector_id,resource_key,action").eq("profile_id", session.userId).is("revoked_at", null),
    service.from("custom_tables").select("id,sector_id,name,slug,description,sector:sectors!custom_tables_sector_id_fkey(name)").is("deleted_at", null).order("name").returns<CustomTable[]>(),
  ]);
  const directorSectorIds = new Set((memberships ?? []).filter((row) => row.role === "diretor").map((row) => row.sector_id));
  const tables = (rawTables ?? []).filter((table) => session.profile.is_president || directorSectorIds.has(table.sector_id) || (grants ?? []).some((grant) => grantMatchesTable({ resourceKey: grant.resource_key, sectorId: grant.sector_id, action: grant.action }, table.id, table.sector_id, "ver")));
  const selected = tables.find((table) => table.id === params.table) ?? tables[0];
  const [{ data: fields }, { data: records }, { data: trash }, { data: views }] = selected ? await Promise.all([
    service.from("custom_table_fields").select("id,name,slug,field_type,is_required,config_json").eq("table_id", selected.id).is("deleted_at", null).order("sort_order").returns<Field[]>(),
    service.from("custom_table_records").select("id,data_json,updated_at,deleted_at").eq("table_id", selected.id).is("deleted_at", null).order("updated_at", { ascending: false }).returns<RecordRow[]>(),
    service.from("custom_table_records").select("id,data_json,updated_at,deleted_at").eq("table_id", selected.id).not("deleted_at", "is", null).order("deleted_at", { ascending: false }).returns<RecordRow[]>(),
    service.from("custom_table_views").select("id,name,view_type").eq("table_id", selected.id).is("deleted_at", null).order("created_at"),
  ]) : [{ data: [] }, { data: [] }, { data: [] }, { data: [] }];
  const manageableSectors = (sectors ?? []).filter((sector) => session.profile.is_president || directorSectorIds.has(sector.id));
  return <main className="members-page builder-page">
    <header className="members-header"><div><p className="eyebrow eyebrow--blue">CONSTRUTOR / NÍVEL B</p><h1>Ferramentas livres por setor.</h1><p>Crie tabelas, campos, registros e visões sem tocar nos módulos financeiros. Tudo é auditável e exclusões seguem para a lixeira.</p></div><Link href="/admin"><ArrowLeft size={16} /> Painel</Link></header>
    <section className="members-summary"><article><Table2 size={24} /><span><strong>{tables.length}</strong><small>tabelas visíveis</small></span></article><article><Database size={24} /><span><strong>{(records ?? []).length}</strong><small>registros ativos</small></span></article></section>
    <section className="members-layout"><article className="members-invite-card"><div className="members-card-title"><FilePlus2 size={19} /><div><span>ESTRUTURA</span><h2>Nova tabela</h2></div></div><form action={createCustomTable} className="members-form"><label>Setor<select name="sectorId" required>{manageableSectors.map((sector) => <option key={sector.id} value={sector.id}>{sector.name}</option>)}</select></label><label>Nome<input name="name" required placeholder="Ex.: Calendário de posts" /></label><label>Identificador técnico <small>opcional; gerado automaticamente</small><input name="slug" placeholder="calendario-posts" autoCapitalize="none" autoCorrect="off" /></label><label>Objetivo<textarea name="description" rows={2} placeholder="Para que esta tabela serve?" /></label><button disabled={!manageableSectors.length} type="submit">Criar tabela</button></form></article>
      <section className="members-list-card"><div className="members-list-card__head"><div><span>MINHAS TABELAS</span><h2>Estruturas disponíveis</h2></div><span>{tables.length} itens</span></div><div className="builder-table-list">{tables.map((table) => <Link key={table.id} href={`/admin/tabelas?table=${table.id}`} className={selected?.id === table.id ? "is-selected" : ""}><strong>{table.name}</strong><small>{table.sector?.name} · {table.description || table.slug}</small></Link>)}{!tables.length && <p className="members-empty">Crie a primeira tabela no setor em que você é diretor.</p>}</div></section></section>
    {selected && <><section className="members-layout builder-detail"><article className="members-invite-card"><div className="members-card-title"><Database size={19} /><div><span>{selected.sector?.name?.toUpperCase()}</span><h2>{selected.name}</h2></div></div><form action={createCustomField} className="members-form"><input type="hidden" name="tableId" value={selected.id} /><label>Nome do campo<input name="name" required placeholder="Ex.: Quantidade mínima por pedido" /></label><label>Identificador técnico <small>opcional; gerado automaticamente</small><input name="slug" placeholder="quantidade-minima-por-pedido" autoCapitalize="none" autoCorrect="off" /></label><label>Tipo<select name="fieldType" defaultValue="text"><option value="text">Texto</option><option value="number">Número</option><option value="date">Data</option><option value="single_select">Seleção única</option><option value="multi_select">Múltipla seleção</option><option value="person">Pessoa</option><option value="checkbox">Caixa de seleção</option></select></label><label>Opções (se seleção)<input name="options" placeholder="Planejado, Em produção, Publicado" /></label><label className="builder-check"><input type="checkbox" name="required" value="true" /> Campo obrigatório</label><button type="submit">Adicionar campo</button></form><form action={createCustomView} className="members-form builder-view-form"><input type="hidden" name="tableId" value={selected.id} /><label>Nova visão<input name="name" required placeholder="Ex.: Em andamento" /></label><label>Formato<select name="viewType" defaultValue="table"><option value="table">Tabela</option><option value="kanban">Kanban (em breve)</option><option value="calendar">Calendário (em breve)</option><option value="gallery">Galeria (em breve)</option></select></label><button type="submit">Salvar visão</button></form></article>
      <section className="members-list-card"><div className="members-list-card__head"><div><span>CAMPOS E VISÕES</span><h2>Estrutura atual</h2></div><span>{(fields ?? []).length} campos</span></div><div className="builder-meta">{(fields ?? []).map((field) => <span key={field.id}>{field.name}<small>{field.field_type}{field.is_required ? " · obrigatório" : ""}</small></span>)}{!(fields ?? []).length && <p className="members-empty">Adicione campos para começar a registrar informações.</p>}</div><div className="builder-meta builder-meta--views">{(views ?? []).map((view) => <span key={view.id}>{view.name}<small>{view.view_type}</small></span>)}</div></section></section>
    <section className="members-layout builder-detail"><article className="members-invite-card"><div className="members-card-title"><FilePlus2 size={19} /><div><span>REGISTRO</span><h2>Novo item</h2></div></div><form action={createCustomRecord} className="members-form"><input type="hidden" name="tableId" value={selected.id} />{(fields ?? []).map((field) => <label key={field.id}>{field.name}{inputForField(field)}</label>)}<button disabled={!(fields ?? []).length} type="submit">Salvar registro</button></form></article>
      <section className="members-list-card"><div className="members-list-card__head"><div><span>REGISTROS</span><h2>{params.trash === "1" ? "Lixeira de 30 dias" : "Itens ativos"}</h2></div><Link href={`/admin/tabelas?table=${selected.id}${params.trash === "1" ? "" : "&trash=1"}`}>{params.trash === "1" ? "Voltar aos ativos" : "Abrir lixeira"}</Link></div><div className="members-table-wrap"><table><thead><tr>{(fields ?? []).map((field) => <th key={field.id}>{field.name}</th>)}<th></th></tr></thead><tbody>{(params.trash === "1" ? trash : records)?.map((record) => <tr key={record.id}>{(fields ?? []).map((field) => <td key={field.id}>{Array.isArray(record.data_json[field.slug]) ? (record.data_json[field.slug] as string[]).join(", ") : String(record.data_json[field.slug] ?? "—")}</td>)}<td><form action={params.trash === "1" ? restoreCustomRecord : trashCustomRecord}><input type="hidden" name="tableId" value={selected.id} /><input type="hidden" name="recordId" value={record.id} /><button title={params.trash === "1" ? "Restaurar" : "Mover para lixeira"} type="submit">{params.trash === "1" ? "Restaurar" : <Trash2 size={15} />}</button></form></td></tr>)}{!((params.trash === "1" ? trash : records)?.length) && <tr><td colSpan={(fields ?? []).length + 1} className="members-empty">Nenhum registro neste momento.</td></tr>}</tbody></table></div></section></section></>}
  </main>;
}
