"use client";

import { ChefHat, Clock3, PackageCheck, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getBrowserClient } from "@/lib/supabase/client";
import { ORDER_STATUS_LABEL } from "@/lib/orders/workflow";
import type { OrderState } from "@/types/domain";

type OdsOrder = { id: string; order_number: number; status: OrderState; fulfillment: string; customer_name: string | null; notes: string | null; created_at: string; pickup_code: string | null; order_items: Array<{ product_name: string; quantity: number }> };
const nextStatus: Partial<Record<OrderState, OrderState>> = { pago: "em_preparo", em_preparo: "pronto", pronto: "entregue" };
const nextLabel: Partial<Record<OrderState, string>> = { pago: "Assumir preparo", em_preparo: "Marcar pronto", pronto: "Entregar pedido" };

export function OdsBoard() {
  const [orders, setOrders] = useState<OdsOrder[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [updatingId, setUpdatingId] = useState<string | null>(null); const [pickupCodes, setPickupCodes] = useState<Record<string, string>>({});
  const loadOrders = useCallback(async () => { setLoading(true); setError(null); try { const supabase = await getBrowserClient(); const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) throw new Error("Sua sessão expirou. Entre novamente."); const response = await fetch("/api/ods/orders", { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json() as { orders?: OdsOrder[]; error?: string }; if (!response.ok) throw new Error(body.error ?? "Não foi possível carregar a fila."); setOrders(body.orders ?? []); } catch (fetchError) { setError(fetchError instanceof Error ? fetchError.message : "Erro ao carregar a fila."); } finally { setLoading(false); } }, []);
  useEffect(() => { let active = true; let cleanup = () => {}; void (async () => { await loadOrders(); try { const supabase = await getBrowserClient(); if (!active) return; const channel = supabase.channel("fsa-ods-orders").on("postgres_changes", { event: "*", schema: "public", table: "orders" }, () => { void loadOrders(); }).subscribe(); cleanup = () => { void supabase.removeChannel(channel); }; } catch (subscriptionError) { if (active) setError(subscriptionError instanceof Error ? subscriptionError.message : "Não foi possível conectar atualizações em tempo real."); } })(); return () => { active = false; cleanup(); }; }, [loadOrders]);
  async function advanceOrder(order: OdsOrder) { const status = nextStatus[order.status]; if (!status) return; setUpdatingId(order.id); try { const supabase = await getBrowserClient(); const { data } = await supabase.auth.getSession(); const response = await fetch("/api/ods/orders", { method: "PATCH", headers: { Authorization: `Bearer ${data.session?.access_token ?? ""}`, "Content-Type": "application/json" }, body: JSON.stringify({ orderId: order.id, status, pickupCode: pickupCodes[order.id] }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Não foi possível atualizar o pedido."); await loadOrders(); } catch (updateError) { setError(updateError instanceof Error ? updateError.message : "Erro ao atualizar o pedido."); } finally { setUpdatingId(null); } }
  return <section className="ods-board"><header><div><p>FILA EM TEMPO REAL</p><h2>Pedidos ativos</h2></div><button type="button" onClick={() => void loadOrders()} disabled={loading}><RefreshCw size={16} className={loading ? "is-spinning" : ""} /> Atualizar</button></header>{error && <p className="ods-error" role="alert">{error}</p>}{loading && <div className="ods-loading">Carregando pedidos...</div>}{!loading && orders.length === 0 && <div className="ods-empty"><ChefHat size={34} /><strong>Nenhum pedido em preparo.</strong><span><Clock3 size={16} /> Novos pedidos pagos aparecerão aqui automaticamente.</span></div>}<div className="ods-board__grid">{orders.map((order) => <article className={`ods-order ods-order--${order.status}`} key={order.id}><header><div><span>#{order.order_number}</span><strong>{ORDER_STATUS_LABEL[order.status]}</strong></div><time>{new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" }).format(new Date(order.created_at))}</time></header><h3>{order.customer_name || "Pedido FSA"}</h3><ul>{order.order_items.map((item, index) => <li key={`${item.product_name}-${index}`}><b>{item.quantity}×</b> {item.product_name}</li>)}</ul><footer><span>{order.fulfillment === "consumo_local" ? "Consumo no local" : "Retirada"}</span>{order.status === "pronto" && order.fulfillment === "retirada" && <label className="ods-pickup-code">Código de retirada<input value={pickupCodes[order.id] ?? ""} onChange={(event) => setPickupCodes((current) => ({ ...current, [order.id]: event.target.value.toUpperCase() }))} inputMode="text" maxLength={10} placeholder="Ex.: A1B2C3D4E5" /></label>}{nextStatus[order.status] && <button type="button" disabled={updatingId === order.id} onClick={() => void advanceOrder(order)}>{updatingId === order.id ? "Atualizando..." : <><PackageCheck size={16} /> {nextLabel[order.status]}</>}</button>}</footer></article>)}</div></section>;
}
