import Link from "next/link";
import { ArrowLeft, CalendarPlus, ClipboardCheck, Filter, Users } from "lucide-react";
import { EVENT_STATUS_LABEL, formatEventDate } from "@/lib/events";
import { formatBRL } from "@/lib/format";
import { requireRole } from "@/lib/auth/require-role";
import { checkInRegistration, createEvent, moveEventStatus } from "./actions";

export const dynamic = "force-dynamic";

type ManagedEvent = { id: string; title: string; status: "divulgando" | "inscricoes_abertas" | "em_andamento" | "encerrado"; starts_at: string | null; venue: string | null; registration_price_cents: number; capacity: number | null; requires_registration: boolean; event_registrations: { count: number }[] };
const nextStatus = { divulgando: "inscricoes_abertas", inscricoes_abertas: "em_andamento", em_andamento: "encerrado" } as const;
type SearchParams = Promise<{ q?: string; status?: string }>;

export default async function AdminEventsPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams; const q = (params.q ?? "").trim().toLowerCase(); const selectedStatus = ["all", "divulgando", "inscricoes_abertas", "em_andamento", "encerrado"].includes(params.status ?? "") ? params.status! : "all";
  const { supabase } = await requireRole(["admin"]); const { data } = await supabase.from("events").select("id,title,status,starts_at,venue,registration_price_cents,capacity,requires_registration,event_registrations(count)").order("starts_at", { ascending: false, nullsFirst: false }).returns<ManagedEvent[]>(); const events = data ?? [];
  return <main className="events-admin-page"><header className="events-admin-header"><div><p className="eyebrow eyebrow--blue">BACKOFFICE / EVENTOS</p><h1>Agenda e operação.</h1></div><Link href="/admin"><ArrowLeft size={16} /> Painel</Link></header><section className="events-admin-layout">
    <article className="event-form-card"><div className="event-form-card__title"><CalendarPlus size={19} /><h2>Novo evento</h2></div><form action={createEvent}><label>Título<input required name="title" placeholder="Ex.: Copa FSA" /></label><label>Descrição<textarea name="description" placeholder="O que acontece neste evento?" /></label><div><label>Início<input name="startsAt" type="datetime-local" /></label><label>Encerramento<input name="endsAt" type="datetime-local" /></label></div><label>Local<input name="venue" placeholder="Ex.: Ginásio FSA" /></label><div><label>Capacidade<input name="capacity" type="number" min="1" placeholder="Sem limite" /></label><label>Inscrição (centavos)<input required name="priceCents" type="number" min="0" defaultValue="0" /></label></div><label className="event-check"><input type="checkbox" name="requiresRegistration" /> Exigir inscrição</label><button type="submit">Criar como divulgando</button></form></article>
    <section className="event-operations"><div className="event-operations__head"><div><span>EVENTOS CADASTRADOS</span><h2>{events.length} na agenda</h2></div><form action={checkInRegistration} className="checkin-form"><ClipboardCheck size={16} /><input name="checkInCode" placeholder="Código de check-in" /><button type="submit">Validar</button></form></div><form className="data-filterbar data-filterbar--compact" method="get"><label><span>Buscar</span><input name="q" defaultValue={q} placeholder="Evento ou local" /></label><label><span>Status</span><select name="status" defaultValue={selectedStatus}><option value="all">Todos os status</option>{Object.entries(EVENT_STATUS_LABEL).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><button type="submit"><Filter size={15} /> Filtrar</button><Link href="/admin/eventos">Limpar</Link></form>{events.filter((event) => (selectedStatus === "all" || event.status === selectedStatus) && (!q || [event.title, event.venue].filter(Boolean).join(" ").toLowerCase().includes(q))).map((event) => <article className="managed-event" key={event.id}><div className={`managed-event__flag status-${event.status}`}><span>{EVENT_STATUS_LABEL[event.status]}</span></div><div className="managed-event__content"><h3>{event.title}</h3><p>{formatEventDate(event.starts_at)} · {event.venue ?? "Local a confirmar"}</p><div><span><Users size={14} /> {event.event_registrations[0]?.count ?? 0}{event.capacity ? `/${event.capacity}` : ""} inscrições</span>{event.requires_registration && <span>{formatBRL(event.registration_price_cents)}</span>}</div></div>{event.status !== "encerrado" && <form action={moveEventStatus}><input type="hidden" name="eventId" value={event.id} /><input type="hidden" name="nextStatus" value={nextStatus[event.status]} /><button type="submit">{nextStatus[event.status] === "inscricoes_abertas" ? "Abrir inscrições" : nextStatus[event.status] === "em_andamento" ? "Iniciar evento" : "Encerrar"}</button></form>}</article>)}{events.filter((event) => (selectedStatus === "all" || event.status === selectedStatus) && (!q || [event.title, event.venue].filter(Boolean).join(" ").toLowerCase().includes(q))).length === 0 && <div className="event-admin-empty">Nenhum evento corresponde aos filtros.</div>}</section></section></main>;
}
