-- MIGRATION-03: remove only the empty, unversioned public.table_name artifact.
--
-- This migration is intentionally fail-closed. It performs no action when the
-- table is already absent, and aborts the full transaction when rows, incoming
-- foreign keys, or dependent views/materialized views are found.
--
-- Rollback reference (only if the experimental artifact must be recreated):
--   create table public.table_name (
--     id bigint generated by default as identity primary key,
--     inserted_at timestamptz not null default now(),
--     updated_at timestamptz not null default now(),
--     data jsonb,
--     name text
--   );
--   alter table public.table_name enable row level security;
-- The original table was empty and unversioned; this reference restores the
-- observed generic shape only, never business data.

do $$
declare
  target_table regclass := to_regclass('public.table_name');
  target_rows bigint := 0;
begin
  if target_table is null then
    raise notice 'public.table_name is absent; no schema cleanup required.';
    return;
  end if;

  select count(*)
  into target_rows
  from public.table_name;

  if target_rows <> 0 then
    raise exception 'Refusing to remove public.table_name because it contains % row(s).', target_rows
      using errcode = 'P0001';
  end if;

  if exists (
    select 1
    from pg_constraint constraint_ref
    where constraint_ref.confrelid = target_table
  ) then
    raise exception 'Refusing to remove public.table_name because another relation has a foreign key to it.'
      using errcode = 'P0001';
  end if;

  if exists (
    select 1
    from pg_depend dependency
    join pg_class dependent_relation on dependent_relation.oid = dependency.objid
    where dependency.refobjid = target_table
      and dependency.deptype = 'n'
      and dependent_relation.relkind in ('v', 'm')
  ) then
    raise exception 'Refusing to remove public.table_name because a view depends on it.'
      using errcode = 'P0001';
  end if;

  drop table public.table_name;
  raise notice 'Removed the empty, unversioned public.table_name artifact.';
end;
$$;
